package ai4.master.project.stanfordParser.sentence;

public enum BlockRole {
	SUBJECT,
	PREDICATE,
	DESCRIPTION,
	OBJECT,
	CONDITION,
	INGREDIENT_TOOL_COLLECTION,
	INGREDIENT_COLLECTION,
	TOOL_COLLECTION;
}
